from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_DATA_DIR = REPO_ROOT / "data"
DEFAULT_WORK_DIR = REPO_ROOT / "outputs"

DEFAULT_IMG_SIZE = 224
DEFAULT_BATCH_SIZE = 32
DEFAULT_NUM_WORKERS = 0
DEFAULT_EPOCHS = 15
DEFAULT_LR = 5e-4
DEFAULT_WEIGHT_DECAY = 1e-6
DEFAULT_SEED = 42
